export { default as StartScreen } from './StartScreen'
export { default as LoginScreen } from './LoginScreen'
export { default as LoginProfessor } from './LoginProfessor'
export { default as RegisterScreen } from './RegisterScreen'
export { default as ResetPasswordScreen } from './ResetPasswordScreen'
export { default as Dashboard } from './Dashboard'
export { default as DashboardProfessor } from './DashboardProfessor'
